const styles = {
  container: { fontFamily: 'system-ui, -apple-system, sans-serif', backgroundColor: '#f8fafc', minHeight: '100vh', padding: '20px', color: '#334155' },
  wrapper: { maxWidth: '1200px', margin: '0 auto' },
  header: { textAlign: 'center', marginBottom: '40px' },
  title: { fontSize: '2rem', fontWeight: 'bold', color: '#1e3a8a', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '12px', marginBottom: '10px' },
  subtitle: { color: '#64748b' },
  layout: { display: 'flex', flexWrap: 'wrap', gap: '24px' },
  controlPanel: { flex: '1 1 300px', backgroundColor: 'white', borderRadius: '12px', padding: '24px', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)', height: 'fit-content' },
  resultsPanel: { flex: '2 1 600px', display: 'flex', flexDirection: 'column', gap: '24px' },
  sectionTitle: { fontSize: '1.25rem', fontWeight: '600', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px', color: '#0f172a' },
  inputGroup: { marginBottom: '20px' },
  label: { display: 'block', fontSize: '0.875rem', fontWeight: '500', marginBottom: '8px' },
  slider: { width: '100%', accentColor: '#2563eb' },
  select: { width: '100%', padding: '8px', borderRadius: '6px', border: '1px solid #cbd5e1', backgroundColor: '#f8fafc', fontSize: '0.9rem', marginBottom: '8px' },
  subPanel: { backgroundColor: '#f1f5f9', padding: '12px', borderRadius: '8px', marginBottom: '20px', border: '1px solid #e2e8f0' },
  checkboxRow: { display: 'flex', alignItems: 'flex-start', gap: '12px', padding: '8px', borderRadius: '6px', transition: 'background-color 0.2s', marginBottom: '8px' },
  checkbox: { marginTop: '4px', width: '16px', height: '16px', cursor: 'pointer' },
  primaryButton: { width: '100%', backgroundColor: '#2563eb', color: 'white', fontWeight: 'bold', padding: '12px 16px', borderRadius: '8px', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', fontSize: '1rem', marginTop: '20px' },
  emptyState: { minHeight: '400px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', border: '2px dashed #cbd5e1', borderRadius: '12px', color: '#94a3b8', backgroundColor: 'rgba(255, 255, 255, 0.5)' },
  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: '16px' },
  statCard: { padding: '16px', borderRadius: '8px', border: '1px solid #e2e8f0', backgroundColor: 'white' },
  chartCard: { backgroundColor: 'white', padding: '20px', borderRadius: '12px', boxShadow: '0 1px 3px 0 rgba(0, 0, 0, 0.1)', border: '1px solid #e2e8f0' },
  insightBox: { borderLeft: '4px solid', padding: '16px', borderRadius: '0 4px 4px 0', fontSize: '0.875rem', display: 'flex', gap: '12px' },
  iconButton: { background: '#f1f5f9', border: 'none', borderRadius: '50%', width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' },
  visContainer: { display: 'flex', gap: '4px', height: '150px', alignItems: 'flex-start', justifyContent: 'center', paddingTop:'10px' },
  visLane: { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', height: '100%' },
  visGate: { width: '100%', height: '12px', borderRadius: '2px', border: '1px solid #94a3b8', marginBottom: '2px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  visQueueTrack: { width: '60%', flex: 1, backgroundColor: '#f1f5f9', borderRadius: '0 0 2px 2px', position: 'relative' },
  visQueueFill: { width: '100%', position: 'absolute', top: 0, left: 0, borderRadius: '0 0 2px 2px', transition: 'height 0.1s ease-in-out' },
  visCount: { fontSize: '0.65rem', color: '#64748b', marginTop: '2px' }
};
export default styles;